services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://opensearch-node:9200
      - ES_USERNAME=master
      - ES_PASSWORD=replace_me
      - ES_TLS_SKIP_HOST_VERIFY=true
      - ES_TLS_ENABLED=true
      - ES_VERSION=7
    networks:
      - otlp-net
    depends_on:
      opensearch-node:
        condition: service_healthy

  opensearch-node:
    image: opensearchproject/opensearch:2.18.0
    restart: always
    container_name: opensearch-node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=replace_me
      - ELASTIC_USERNAME=master
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=UserFeedback123!@#
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - otlp-net

  # optional for opensearch
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    restart: always
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]'
      - 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true'
    depends_on:
      - opensearch-node
    networks:
      - otlp-net

networks:
  otlp-net:
    driver: bridge
