services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=jaeger
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
    networks:
      - go-otlp-app
networks:
  go-otlp-app:
    driver: bridge
